ProjetoDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),
    path('__debug__/', include('debug_toolbar.urls')), #31/10
    
]

cadastros/urls.py
from django.urls import path
from .views import CampoCreaete, RobosCreate
from .views import CampoUpdate, RobosUpdate
from .views import CampoDelete, RobosDelete
from .views import CampoList, RobosList


urlpatterns = [
    path('cadastrar/campo', CampoCreaete.as_view(), name="cadastrar-campo"),
    path('cadastrar/robos', RobosCreate.as_view(), name="cadastrar-robos"),
    
    path('editar/campo/<int:pk>/', CampoUpdate.as_view(), name="editar-campo"),
    path('editar/robos/<int:pk>/', RobosUpdate.as_view(), name="editar-robos"),
    
    path('excluir/campo/<int:pk>/', CampoDelete.as_view(), name="excluir-campo"),
    path('excluir/robos/<int:pk>/', RobosDelete.as_view(), name="excluir-robos"),
    
    path('listar/campo/<int:pk>/', CampoList.as_view(), name="listar-campo"),
    path('listar/robos/<int:pk>/', RobosList.as_view(), name="listar-robos"),
]

paginas/urls.py
from unicodedata import name
from django.urls import path
from .views import IndexView, SobreView, RoboView

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('sobre/', SobreView.as_view(), name="sobre"),
    path('robos/', RoboView.as_view(), name="robos"),
]

cadastros/models.py
from django.db import models

# Create your models here.
class Campo(models.Model):
    nome = models.CharField(max_length=50, verbose_name="Nome")
    descricao = models.CharField(max_length=150, verbose_name="Descricao")
    
    def __str__(self):
        return "{} ({})".format(self.nome, self.descricao)
    
class Robos(models.Model):
    numero = models.IntegerField(verbose_name="Numero")
    descricao = models.CharField(max_length=150, verbose_name="Descricao")
    pontos = models.DecimalField(decimal_places=1, max_digits=4)
    detalhes = models.CharField(max_length=100)
    
    campo = models.ForeignKey(Campo, on_delete=models.PROTECT)
    def __str__(self):
        return "{} ({})".format(self.numero, self.campo)

paginas/models.py
from django.db import models

# Create your models here.

cadastros/views.py
from dataclasses import fields
from re import template
import django
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from .models import Campo, Robos

from django.urls import reverse_lazy

# Create your views here.
class CampoCreaete(CreateView):
    model= Campo
    fields= ['nome', 'descricao']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('index')
    
class RobosCreate(CreateView):
    model= Robos
    fields = ['numero', 'descricao', 'pontos', 'detalhes', 'campo']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('index')
    
####

class CampoUpdate(UpdateView):
    model = Campo
    fields = ['nome', 'descricao']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('index')
    

class RobosUpdate(UpdateView):
    model = Robos
    fields = ['numero', 'descricao', 'pontos', 'detalhes', 'campo']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('index')

####


class CampoDelete(DeleteView):
    model = Campo
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('index')


class RobosDelete(DeleteView):
    model = Robos
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('index')

####


class CampoList(ListView):
    model = Campo
    template_name = 'cadastros/listas/campo.html'
    
    #def get_queryset(self):
        #self.object_list = Campo.objects.select_related('nome', 'descricao'); #Exemplo de Select Related
        #return self.object_list;


class RobosList(ListView):
    model = Robos
    template_name = 'cadastros/listas/robos.html'

paginas/views.py
from django.views.generic import TemplateView

# Create your views here.
class IndexView(TemplateView):
    template_name = "paginas/index.html"
    
class SobreView(TemplateView):
    template_name = "paginas/sobre.html"
    
class RoboView(TemplateView):
    template_name = "paginas/modelo-robos.html"

cadastros/templates/cadastros/form-excluir.html
{% extends 'paginas/modelo-robos.html' %}

{% load static %}

{% block conteudo %}
    <h3>Deletar Registro</h3>

    <p class="lead">
        Confirme para excluir o registro definitivamente
    </p>

    <form action="" method="POST">
        <p>
            Deseja excluir o registro: <b>{{ object }}</b> ?
        </p>

        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="btn btn-danger">Excluir</button>
    </form>

{% endblock conteudo %}

cadastros/templates/cadastros/form.html
{% extends 'paginas/modelo-robos.html' %}

{% load static %}

{% block conteudo %}
    <h3>Cadastro</h3>

    <p class="lead">
        Preencha os Campos Obrigatorios
    </p>

    <form action="" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="btn btn-dark">Cadastrar</button>
    </form>

{% endblock conteudo %}

{% block scripts %}

<script src="{% static "js/jquery.mask.min.js" %}"></script>

<script>

    //Teste Maskara
    $(document).ready(function(){

        //exemplo de como modificar a mascara segundo a condição
        /*var SPMaskBehavior = function (val) {
        return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
        },
        spOptions = {
        onKeyPress: function(val, e, field, options) {
            field.mask(SPMaskBehavior.apply({}, arguments), options);
            }
        };

        $('.sp_celphones').mask(SPMaskBehavior, spOptions);*/

        // Exemplo de padrão data com input e " =* "
        //$("input[id=*data_]").mask("000_00000");

        $("#id_descricao").mask("AAAA_AAAA");
        
    });

    
</script>


{% endblock %}

cadastros/templates/cadastros/listas/campo.html
{% extends 'paginas/modelo-robos.html' %}

{% load static %}

{% block conteudo %}
    <h3>Listar Campos Cadastrados</h3>

    <hr>
    <div class="table-responsive">
        <table class="table table-striped">
            <tr>
                <th>ID/th>
                <th>Nome</th>
                <th>Descricao</th>
                <th>Opcoes</th>
            </tr>

            {% for campo in object_list %}
                <tr>
                    <td>{{ campo.pk }}</td>
                    <td>{{ campo.nome }}</td>
                    <td>{{ campo.descricao }}</td>
                    <td>
                        <a href="{% url 'editar-campo' campo.pk %}" class="btn btn-warning btn-sm">Editar</a>
                        <a href="{% url 'excluir-campo' campo.pk %}" class="btn btn-danger btn-sm">Excluir</a>
                    </td>
                </tr>
                

            {% empty %}
                <tr>
                    <td colspan="3">Nenhum campo registrado</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    

{% endblock conteudo %}

cadastros/templates/cadastros/listas/robos.html
{% extends 'paginas/modelo-robos.html' %}

{% load static %}

{% block conteudo %}
    <h3>Listar Robos Cadastrados</h3>

    <hr>
    <div class="table-responsive">
        <table class="table table-striped">
            <tr>
                <th>ID/th>
                <th>numero</th>
                <th>Descricao</th>
                <th>Pontos</th>
                <th>Opcoes</th>
            </tr>

            {% for robos in object_list %}
                <tr>
                    <td>{{ robos.pk }}</td>
                    <td>{{ robos.numero }}</td>
                    <td>{{ robos.descricao }}</td>
                    <td>{{ robos.pontos }}</td>
                    <td>
                        <a href="{% url 'editar-robos' robos.pk %}" class="btn btn-warning btn-sm">Editar</a>
                        <a href="{% url 'excluir-robos' robos.pk %}" class="btn btn-danger btn-sm">Excluir</a>
                    </td>
                </tr>
                

            {% empty %}
                <tr>
                    <td colspan="3">Nenhum robo registrado</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    

{% endblock conteudo %}

paginas/templates/index.html
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device-width, initial-scale-1.0">
    <title>Pagina Inicial</title>

</head>
<body>
    <h3> Bem VINDOS </h3>
</body>

paginas/templates/paginas/index.html
{% extends 'paginas/modelo-robos.html' %}

{% load static %}

{% block titulo %}
    <title>Pagina Inicial</title>
{% endblock titulo %}

{% block conteudo %}
    <h1>BEM VINDO PILOTO!</h1>

    <a name="BotaoEsconderDiv" id="BotaoMostrarDiv1" class="btn btn-primary" role="button"> MostrarDiv</a>

    <a name="BotaoEsconderDiv" id="BotaoMostrarDiv2" class="btn btn-primary"  role="button"> MostrarDiv2</a>

    <a name="BotaoEsconderDiv" id="BotaoMostrarDiv3" class="btn btn-primary"  role="button"> MostrarDiv3</a>

    


    <div class="div-teste p-2 my-2 bg-secondary" id="divMostrar1">
        Novas Promoções
    </div>

    <div class="div-teste p-2 my-2 bg-primary" id="divMostrar2" style="display:none" >
        Alertas
    </div>

    <div class="form-group">
      <label for=""></label>
      <input type="text"
        class="form-control" name="" id="input-text" aria-describedby="helpId" placeholder="Digite aqui" value="40">
      <small id="helpId" class="form-text text-muted">Texto de ajuda</small>
    </div>

    <img src="{% static 'img/imagem.jpg' %}" width="1000"alt="">
{% endblock conteudo %}

{% block scripts %}

<script>

    $(document).ready(function(){
        alert("START");

        $("#BotaoMostrarDiv1").click(function(){

            $("#divMostrar2").hide();
            $("#divMostrar1").fadeIn()();

        });

        $("#BotaoMostrarDiv2").click(function(){

            $("#divMostrar1").hide();

            var v = $("#input-text").val(); // Valor do Input
            
            $("#divMostrar2").text(v); // seta texto em div

            $("#divMostrar2").removeClass('bg-success').addClass('bg-primary')

            $("#divMostrar2").fadeIn();

        });

        $("#BotaoMostrarDiv3").click(function(){

            $("#divMostrar1").hide();
            
            $("#divMostrar2").removeClass('bg-primary').addClass('bg-success'); // seta texto em div

            $("#divMostrar2").fadeIn();

        });

        $("#divMostrar1").mouseenter(function(){

            $("#divMostrar1").removeClass('bg-secondary').addClass('bg-success');

        });

        $("#divMostrar1").mouseout(function(){

            $("#divMostrar1").removeClass('bg-success').addClass('bg-secondary');

        });
    });

</script>

{% endblock scripts %}

paginas/templates/paginas/modelo-robos.html
{% load static %}

<!doctype html>
<html lang="pt-br" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Rafael H. D. Zottesso">

    {% block titulo %}
    <title>:: SisProg ::</title>
    {% endblock %}

    <!-- Ícone do favicon -->
    <link href="{% static 'img/favicon.gif' %}" rel="shortcut icon" type="image/x-icon" />


    <!-- Importação do Bootstrap 4 e do Font awesome -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <!-- CSS adicional -->
    <link href="{% static 'css/ifpr.css' %}" rel="stylesheet">

    <!-- CSS datatable -->
    <link href="{% static 'css/datatables.min.css' %}" rel="stylesheet">

    <!-- Importação do Datatables -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.22/datatables.min.css" />

    <!-- Ícone na barra de abas -->
    <!-- <link rel="shortcut icon" href="{% static 'img/favicon.png' %}"> -->

    <!-- Bloco destinado aos estilos para cada página -->
    {% block styles %}

    {% endblock %}

</head>

<body class="d-flex flex-column h-100">
    <main role="main" class="flex-shrink-0">


        <!-- Bloco com a logo da cidade -->
        {% block logo %}
        <!-- <div class="container-fluid bg-white">
            <div class="container border-bottom border-light p-3">
                <img src="{% static 'img/BannerGundamlogo.png' %}" alt="" style="max-height: 65px;" class="img-fluid">
            </div>

        </div> -->
        {% endblock %}


        <!-- Bloco com o menu principal -->
        {% block menu %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-ifpr font-115 shadow">

            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'img/gundam-circle.png' %}" height="40" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav mr-auto">
                        <a name="Area" id="area"  class="btn bg-transparent" href="" width="20000" role="button" >______________________________________</a>
                        <a name="Inicio" id="Inicio" class="btn btn-dark" href="{% url 'index' %}" role="button" >Inicio</a>
                        <!--{% if request.user.is_authenticated %}
                        {% endif %}-->
                        <a name="Area" id="area"  class="btn bg-transparent" href="" width="20000" role="button" >___</a>
                        <a name="Sobre" id="sobre"  class="btn btn-dark" href="{% url 'sobre' %}" role="button" >Sobre</a>
                        <a name="Area" id="area"  class="btn bg-transparent" href="" width="20000" role="button" >___</a>
                        <a name="Sobre" id="sobre"  class="btn btn-dark" href="{% url 'cadastrar-robos'%}" role="button" >CadastrarRobos</a>
                        <a name="Area" id="area"  class="btn bg-transparent" href="" width="20000" role="button" >___</a>
                        <a name="Sobre" id="sobre"  class="btn btn-dark" href="{% url 'cadastrar-campo'%}" role="button" >CadastrarCampos</a>
                        <a name="Area" id="area"  class="btn bg-transparent" href="" width="20000" role="button" >___</a>
                        <a name="Sobre" id="sobre"  class="btn btn-dark" href="{% url 'listar-robos' 1 %}" role="button" >ListaRobos</a>
                        <a name="Area" id="area"  class="btn bg-transparent" href="" width="20000" role="button" >___</a>
                        <a name="Lista" id="lista"  class="btn btn-dark" href="{% url 'listar-campo' 1 %}" role="button" >ListaCampo</a>
                        <a name="Area" id="area"  class="btn bg-transparent" href="" width="20000" role="button" >___</a>
                        
                        
                    </ul>

                    <ul class="navbar-nav">

                        {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink"
                                role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-user-circle" aria-hidden="true"></i>
                                <span id="username">{{ request.user }}</span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" >
                                    <i class="fa fa-user" aria-hidden="true"></i>
                                    Meus dados</a>
                                <a class="dropdown-item" href="#">
                                    <i class="fa fa-lock" aria-hidden="true"></i>
                                    Alterar senha</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item">
                                    <i class="fa fa-sign-out" aria-hidden="true"></i>
                                    Sair</a>
                            </div>
                        </li>
                        {% else %}
                        <li class="nav-item ">
                            <a class="nav-link" href="">
                                <i class="fa fa-user-plus" aria-hidden="true"></i>
                                Registrar
                            </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="">
                                <i class="fa fa-sign-in" aria-hidden="true"></i>
                                Login
                            </a>
                        </li>
                        {% endif %}

                    </ul>
                </div>

                <!-- fim do container -->
            </div>
        </nav>
        {% endblock %}


        <!-- Bloco de conteúdo -->
        <div class="container py-5">
            {% block conteudo %}
            <h3>Página inicial</h3>
            {% endblock %}
        </div>

    </main>

    <footer class="mt-auto">

        <!-- Bloco acima do rodapé com links -->
        {% block rodape-links %}
        <div class="container-fluid bg-ifpr text-white p-3">
            <div class="container">
                <div class="row">
                    <div class="col-sm">
                        <h5>O Município</h5>
                        <ul class="list-unstyled">
                            <li><a href="#" class="text-white">Link 1</a></li>
                            <li><a href="#" class="text-white">Link 2</a></li>
                            <li><a href="#" class="text-white">Link 3</a></li>
                        </ul>
                    </div>
                    <div class="col-sm">
                        <h5>Serviços</h5>
                        <ul class="list-unstyled">
                            <li><a href="#" class="text-white">Link 1</a></li>
                            <li><a href="#" class="text-white">Link 2</a></li>
                            <li><a href="#" class="text-white">Link 3</a></li>
                        </ul>
                    </div>
                    <div class="col-sm">
                        <h5>Acesso rápido</h5>
                        <ul class="list-unstyled">
                            <li><a href="#" class="text-white">Link 1</a></li>
                            <li><a href="#" class="text-white">Link 2</a></li>
                            <li><a href="#" class="text-white">Link 3</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}


        <!-- Rodapé -->
        {% block rodape %}
        <div class="container-fluid bg-light text-center p-3">
            <div class="row">
                <div class="col-md-4 mx-auto text-center">
                    <img src="{% static 'img/ifpr.png' %}" height="48" class="float-left" alt="">
                    <p>
                        <span class="lead">Gundam</span><br>
                        <span>Desenvolvido por Cristian Ceccon</span>
                    </p>
                </div>

                </p>
            </div>
            {% endblock %}

    </footer>


    <!-- Importação do JS -->
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/datatables.min.js' %}"></script>

    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.22/datatables.min.js"></script>

    <script>
        // Comando para paginação "table"
        $(document).ready(function(){
            $("table").DataTable();
        });
    </script>

    <!-- Bloco destinado aos scripts para cada página -->
    {% block scripts %}

    {% endblock %}

</body>

</html>

paginas/templates/paginas/modelo.html
{% load static %}

<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device-width, initial-scale-1.0">
    <title>Pagina Inicial</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

</head>
<body>
    {% block menu %}
    <div class="bg light">
        Codigo do meu menu
    </div>
    {% endblock %}

    {% block destaque %}
    <div class="bg secondary">
        Figura de destaque
    </div>
    {% endblock %}

    <div class="container">
    {% block conteudo %}
        <h3> Template de Modelo </h3>

        <p>conteudo do site</p>
    {% endblock %}
    </div>
    

    {% block rodape %}
    <div class="">
        rodape
    </div>
    {% endblock %}
    

    <script = "{% static 'js/jsquery-3.4.1.min.js' %}"></script>
    <script = "{% static 'js/bootstrap.min.js' %}"></script>
    <script = "{% static 'js/popper.js' %}"></script>
</body>

paginas/templates/paginas/sobre.html
{% extends 'paginas/modelo-robos.html' %}

{% block titulo %}
    <title>Sobre o Projeto</title>
{% endblock titulo %}

{% block conteudo %}
    <h3>Sobre o sistema</h3>
    
    <p>Lista Pagina vai descrever projeto</p>
{% endblock conteudo %}